### ISSUE TITLE
[Web]: Tracking issue

### ISSUE THREAD

**Issue by ekrembal** [bounswe/bounswe2024group3#259]
### Todos:

- [x] #262 
- [x] #304  
- [x] #263
- [x] #264 
- [x] #266
- [ ] #267
- [ ] Create a component for post
- [ ] Create a component for lyrics
- [ ] Create a component for Spotify embedded music player
- [ ] Create a component for a suggested item (this can be song, playlist, event)
- [ ] Create feed page
- [ ] Create song page
- [ ] Create playlist page
- [ ] Create events page

**Comment by eyusufatik** [comment]
as per our discussion, closing smaller tracking issues.
