### ISSUE TITLE
[Planning]: Milestone 2 Tracking issue

### ISSUE THREAD

**Issue by burkaykinik** [bounswe/bounswe2024group3#371]
### Post creation
- [x] #395
- [ ] #404
- [ ] #391
- [x] #389
- [x] #405

### Search (based on post title) and filtering (post type)
- [x] #402
- [x] #419
- [x] #403
- [ ] #423
- [x] #390
- [x] #417

### Lyrics on song posts
- [ ] #407
- [ ] #424
- [x] #394
- [x] #406

### Recommendation
- [x] #408
- [ ] #425 
- [x] #409
- [ ] #426
- [x] #397
- [x] #416

### Follow/Unfollow and for you page (based on following)
- [x] #410
- [ ] #427
- [x] #399
- [x] #400
- [x] #413
- [x] #414

### Like / Dislike post
- [x] #411
- [ ] #428
- [x] #412
- [ ] #429
- [x] #401
- [x] #415

### Testing
- [ ] #420
- [x] #421
- [ ] #422
- [x] #470

**Comment by eyusufatik** [comment]
From our discussion here's a list of our features to implement for milestone 2:

- Post creation
- Post tagging
- Search (based on post title) and filtering (post type)
- Lyrics on song posts
- Recommendation
- Follow/Unfollow and for you page (based on following)
- Proper like dislike

**Comment by ekrembal** [comment]
We also need testing as TA said, for web

- [ ] [Web] Research Web Vitals for React
- [ ] [Web] Unit test for req util function
- [ ] [Web] Automated test with seleniom

**Comment by Abdusshh** [comment]
We also need testing for mobile as well

- [ ] [Mobile] Unit tests for screens
